### ISSUE TITLE
Support for Multiple XML elements? (Multiple Recipients)

### ISSUE THREAD

**Issue by jaypoc** [CumberlandGroup/node-ews#47]
This is my first exposure to EWS, and I'm using this to send out email through an exchange account. It works when I send to one recipient, but I am unable to send to multiple recipients.

How can I pass multiple recipients? Looks like the XML would just have repeat EmailAddress elements, but when I try that here it only sends to the first one. (I odn't believe JSON doesn't support like-named elements)

(Sorry Coffeescript here)
````
ewsArgs =
  attributes:
    MessageDisposition: "SendAndSaveCopy"
  SavedItemFolderId:
    DistinguishedFolderId:
      attributes:
        Id: "sentitems"
  Items:
    Message:
      ItemClass: "IPM.Note"
      Subject: "[Automation] Test email."
      Body:
        attributes:
          BodyType : "Text"
        $value: "This is a test email"
      ToRecipients:
        Mailbox:
          EmailAddress: "address1@example.com"
      IsRead: false
````
